### PR TITLE
can create subcommands

### PR DESCRIPTION
**Pull request by yanick**
For #30

### CODE REVIEW

**Comment by maros** [comment]
Thank you for you pull request. Indeed a great idea to use whitespaces to separate commands from subcommands. However, I will need to refactor some code before I can merge your PR. (eg. it probably is much easier to pass the just the unaltered ParsedArgv object to command_find instead of shifting off the first command + ParsedArgv

**Comment by yanick** [comment]
> it probably is much easier to pass the just the unaltered ParsedArgv object to command_find instead of shifting off the first command + ParsedArgv

Indeed. I mostly wanted to wedge in the functionality while disturbing as little as possible of what was already there. So, yeah, there's room to polish things a little bit more. But I'm quite happy to see how simple the change was, at the end. :-)

**Comment by maros** [comment]
I ran into some issues in cases where other classes (eg. roles) were nested in the command namespace. To address this issue I had to add a 'app_exclude' keyword (see c8b43338786e97e00f4caabc950af699b96c8fe7)

Since I had to do some refactoring to your original PR (eg. slightly change the API of MooseX::App::ParsedArgv), I just copied your changes to a new subcommand branch. Please have a look at it.

**Comment by maros** [comment]
Also need to add fuzzy command name matching tests and a subcommand help (in the parent command) before I can finally merge this into master.

**Pull request closed without merging**
