### PR TITLE
Use Dist::Zilla

### PR DESCRIPTION
**Pull request by pplu**
Hi,

   Trying to develop PR #57, I couldn't get `perl Makefile.PL` to work, since the `inc/` directory is not committed in this repo, and the ones I installed didn't seem to work. I've changed this module to use Dist::Zilla (since that's what I know), and added a Makefile that builds the MooseX::App cpan dist. To develop MooseX::App you basically need to clone, and execute `carton` to get all dependencies installed in a local directory. After that, `carton exec -- prove -I lib t/` can execute tests. I find this to be a convenient enough setup for me at least. Since I couldn't contribute changes without going through this process, I decided to do a second PR with the conversion to Dist::Zilla just in case you found it interesting for MooseX::App.

   As an extra, there is also another target to build a README.md from POD, so GitHub can display the documentation with format.

### CODE REVIEW

**Comment by maros** [comment]
Thank you for your contribution.

Since I'm not familiar with Dist::Zilla I'd like to evaluate this pull request before merging it.
inc/ is only part of the release and usually created on the developer box by running perl Makefile.PL (unfortunately for this to work, and partly due to a limitation of  Module::Install, the package Module::Install::ReadmeFromPod needs to be present on the developer' box)

**Comment by pplu** [comment]
Don't feel obligated to adopt Dist::Zilla if it's not your usual workflow. If you have any doubts, I can try to help out.

Do you have any idea of when you'll upload a new release? (I'm very interested in having the deterministic order of bash_completion published)

**Comment by maros** [comment]
I'll release a new version in the next couple of days

**Comment by maros** [comment]
Released as 1.41

**Pull request merged**
