### PR TITLE
Add ability to negate boolean options #29

### PR DESCRIPTION
**Pull request by biologghe**

### CODE REVIEW

**Comment by perlpunk** [comment]
Just a note: check if BashCompletion/ZshCompletion need adjustments for this too. I can have a look.

**Comment by biologghe** [comment]
Good point. I did not check on that. POD was not updated either. Sorry, rather quick fix because I needed it badly.

**Comment by maros** [comment]
Thank you for your contribution.

**Comment by perlpunk** [comment]
Hm, I think the `--no-` should probably be optional. Things like `--no-help` don't really make sense, and they would just confuse in completion.
But for the completion generation I'd have to know which options should be negated and which not.

**Comment by maros** [comment]
Yes, I believe so too. I think this can be handled via parser hints generated by command_parser_hints and passed to MooseX::App::ParsedArgv

**Comment by maros** [comment]
See https://github.com/maros/MooseX-App/tree/negate_boolean for a more refined approach. However still not quite content with the result since these changes makes the MooseX::App::ParsedArgv::Element to attributes mapping code in command_parse_options a nightmare (even more than it already was).

**Comment by biologghe** [comment]
Great, thank you !

**Comment by biologghe** [comment]
BTW, you can safely remove my name from the credits, I don't deserve any. I only triggered this feature :-) Your refinement is much nicer and deals with Tina's suggestion to make negation optional. Thank you both, appreciated.
Cheers,
Marc

**Pull request merged**
